[package]
name = "advanced-todo-list"
version = "1.0.0"
authors = []

[addresses]
advanced_todo_list_addr = "_"

[dev-addresses]
advanced_todo_list_addr = "0x111"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework"}

[dev-dependencies]
